var gradients = [
  {
    "name":"Partly Cloudy",
    "colour1":"#DAE2F8",
    "colour2":"#D6A4A4"
  },
  {
    "name":"Sunny",
    "colour1":"#FF4E50",
    "colour2":"#F9D423"
  },
  {
    "name":"Cloudy",
    "colour1":"#ECE9E6",
    "colour2":"#FFFFFF"
  },
  {
    "name":"Snowing",
    "colour1":"#E6DADA",
    "colour2":"#274046"
  },
  {
    "name":"Rain",
    "colour1":"#616161",
    "colour2":"#9BC5C3"
  },
  {
    "name":"Fog",
    "colour1":"#757F9A",
    "colour2":"#D7DDE8"
  }
];